per_listener_settings true
log_type all

# Plain MQTT (internal, for HAProxy without re-encryption)
listener 1883
protocol mqtt
allow_anonymous true

# MQTT over TLS (for HAProxy with re-encryption)
listener 8883
protocol mqtt
allow_anonymous true
cafile /mosquitto/certs/ca.crt
keyfile /mosquitto/certs/server.key
certfile /mosquitto/certs/server.crt
