# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Build iOS"
  lane :incbuild do
    increment_build_number(
      xcodeproj: "MQTTAnalyzer.xcodeproj"
    )
  end

  lane :archive do
    gym()
    #build_app(
    #  workspace: "MQTTAnalyzer.xcworkspace", 
    #  scheme: "MQTTAnalyzer"
    #)
    upload_to_app_store(
      #username: "#{ENV['FASTLANE_USER']}",
      platform: "ios", 
      ipa: "MQTTAnalyzer.ipa",
      skip_screenshots: true
    )
  end

  lane :screenshots do
    capture_screenshots(workspace: "MQTTAnalyzer.xcworkspace", scheme: "MQTTAnalyzer")
  end
end

platform :mac do
  desc "Build macOS"
  lane :archive do
    gym(
      catalyst_platform: "macos",
      destination: "generic/platform=macOS,variant=Mac Catalyst",
    )
    upload_to_app_store(
      #username: "#{ENV['FASTLANE_USER']}",
      platform: "osx", 
      pkg: "MQTTAnalyzer.pkg",
      skip_screenshots: true
    )
  end

  lane :screenshots do
    capture_screenshots(workspace: "MQTTAnalyzer.xcworkspace", scheme: "MQTTAnalyzer")
  end
end
