# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MQTTAnalyzer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MQTTAnalyzer
  use_frameworks! # Add this if you are targeting iOS 8+ or using Swift
  
  pod 'Moscapsule', :git => 'https://github.com/flightonary/Moscapsule.git'
  pod 'OpenSSL-Universal', '1.0.2.20'
  
	pod 'CocoaMQTT', '1.3.0-rc.1'
	pod 'CocoaMQTT/WebSockets', '1.3.0-rc.1'
	
  pod 'RealmSwift', '~> 4.4.1'
  pod 'IceCream'

  pod 'Highlightr', :git => 'https://github.com/raspu/Highlightr.git'
  
  pod 'swift-petitparser'
  
  pod 'SwiftyJSON'

  pod 'SwiftLint'
  
  target 'MQTTAnalyzerTests' do
	inherit! :search_paths
	# Pods for testing
  end

#  target 'MQTTAnalyzerUITests' do
#	inherit! :search_paths
#	# Pods for testing
#  end

end
