# Uncomment the next line to define a global platform for your project
platform :ios, '15.2'

post_install do |installer|
 installer.pods_project.targets.each do |target|
	target.build_configurations.each do |config|
	 config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
	end
 end
end

def shared_pods
	$cocoaMQTTVersion = 'apple-network'
	$cocoaMQTTURL = 'https://github.com/philipparndt/CocoaMQTT.git'
	
	pod 'CocoaMQTT', :git => $cocoaMQTTURL, :branch => $cocoaMQTTVersion
	pod 'CocoaMQTT/WebSockets', :git => $cocoaMQTTURL, :branch => $cocoaMQTTVersion
	
	#pod 'CocoaMQTT', :path => '~/dev/oss/CocoaMQTT'
	#pod 'CocoaMQTT/WebSockets', :path => '~/dev/oss/CocoaMQTT'
	

	pod 'RealmSwift', '~> 10.7.0'
	pod 'IceCream', '2.0.4'

	pod 'Highlightr', :git => 'https://github.com/raspu/Highlightr.git', :tag => '2.1.2'
	
	pod 'CodeEditor', :git => 'https://github.com/ZeeZide/CodeEditor.git'
	
	pod 'swift-petitparser'
	
	pod 'SwiftyJSON'

	pod 'SwiftLint'
	
	pod 'GRDB.swift', '5.22.2'
end

target 'MQTTAnalyzer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MQTTAnalyzer
  use_frameworks! # Add this if you are targeting iOS 8+ or using Swift
  
	shared_pods
	
  
  target 'MQTTAnalyzerTests' do
	inherit! :search_paths
	# Pods for testing
  end

  target 'MQTTAnalyzerUITests' do
	inherit! :search_paths
	shared_pods
  end
end
