name: 'Fastlane scan'

on: 
  workflow_dispatch:

jobs:
  test:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master

    - name: Install ZX
      run: |
        npm install -g zx
    
    - name: Install Mosquitto
      run: |
        ci/start-mosquitto.mjs
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_13.2.app
    
    - name: Install Dependences
      working-directory: src
      run: |
        pod repo update
        pod install
      shell: bash
    
    - name: Create screenshots
      working-directory: src
      run: |
        fastlane scan
        
    - name: Stop Mosquitto
      if: always()
      run: |
        ci/stop-mosquitto.mjs

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test_output
        path: src/fastlane/test_output
