name: 'Create screenshots'

on: 
  workflow_dispatch:

jobs:
  screenshots:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master

    - name: Install ZX
      run: |
        npm install -g zx
    
    - name: Install ActiveMQ
      run: |
        ci/start-active-mq.mjs

    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_13.2.app
    
    - name: Install Dependences
      working-directory: src
      run: |
        pod repo update
        pod install
      shell: bash
    
    - name: Create screenshots
      run: |
        bash create-screenshots.sh

    - name: Stop ActiveMQ
      if: always()
      run: |
        ci/stop-active-mq.mjs

    - uses: actions/upload-artifact@v2
      with:
        name: screenshots
        path: src/fastlane/screenshots/**/*.png
        retention-days: 5
