name: 'Create screenshots'

on: 
  workflow_dispatch:

jobs:
  screenshots:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master

    - name: Install ZX
      run: |
        npm install -g zx
    
    - name: Install Mosquitto
      run: |
        ci/start-mosquitto.mjs

    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_13.2.app
    
    - name: Install Dependences
      working-directory: src
      run: |
        pod repo update
        pod install
      shell: bash
    
    - name: Install Imagemagick
      working-directory: src
      run: |
        brew update 
        brew install imagemagick
      shell: bash

    # No support for Package.resolve v2 on GitHub
    - name: Remove Package.resolve 
      working-directory: src
      run: |
        rm ./MQTTAnalyzer.xcworkspace/xcshareddata/swiftpm/Package.resolved

    - name: Create screenshots
      run: |
        bash create-screenshots.sh

    - name: Stop Mosquitto
      if: always()
      run: |
        ci/stop-mosquitto.mjs

    - uses: actions/upload-artifact@v3
      with:
        name: screenshots
        path: screenshots/**/*.png
        retention-days: 5
