name: 'Build'

on: 
  workflow_dispatch:
  push:
    paths:
      - 'src/**'

jobs:
  test:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Install ZX
      run: |
        npm install -g zx

    - name: Install ActiveMQ
      run: |
        ci/start-active-mq.mjs

    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_13.2.app
    
    - name: Install Dependences
      working-directory: src
      run: |
        pod repo update
        pod install
      shell: bash
    
    - name: Test
      working-directory: src
      run: |
        xcodebuild test -enableCodeCoverage YES \
        -workspace MQTTAnalyzer.xcworkspace \
        -scheme MQTTAnalyzer \
        -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2'

    - name: Stop ActiveMQ
      if: always()
      run: |
        ci/stop-active-mq.mjs
