name: 'Build'

on: 
  workflow_dispatch:
#  push:
#    paths:
#      - 'src/**'

jobs:
  test:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_13.2.app

    - name: Install Dependences
      working-directory: src
      run: |
        pod repo update
        pod install
      shell: bash
    
    # No support for Package.resolve v2 on GitHub
    - name: Remove Package.resolve 
      working-directory: src
      run: |
        rm ./MQTTAnalyzer.xcworkspace/xcshareddata/swiftpm/Package.resolved

    - name: iOS Tests
      working-directory: src
      run: |
        xcodebuild test -enableCodeCoverage YES \
        -workspace MQTTAnalyzer.xcworkspace \
        -scheme MQTTAnalyzer \
        -testPlan UnitTestPlan \
        -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2'

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: test_output
        path: src/fastlane/test_output
    # no public macOS 12 runner available
    #- name: macOS Tests
    #  working-directory: src
    #  run: |
    #    fastlane mac tests
