name: 'Test'
on:
   workflow_dispatch:

jobs:
  test:
    runs-on: macOS-latest

    steps:
    - uses: actions/checkout@master
    
    - name: Set XCode Version
      run: sudo xcode-select -s /Applications/Xcode_13.2.app

     # No support for Package.resolve v2 on GitHub
    - name: Remove Package.resolve 
      working-directory: src
      run: |
        rm ./MQTTAnalyzer.xcworkspace/xcshareddata/swiftpm/Package.resolved

    - name: Install Dependences
      working-directory: src
      run: |
        pod repo update
        pod install
      shell: bash

    - name: Test
      working-directory: src
      run: |
        xcodebuild test -enableCodeCoverage YES \
        -workspace MQTTAnalyzer.xcworkspace \
        -scheme MQTTAnalyzer \
        -testPlan UnitTestPlan \
        -destination 'platform=iOS Simulator,name=iPhone 13,OS=15.2'
